<?php

use Illuminate\Database\Seeder;

class productSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([[
            'nama' => 'Dear Allah',
            'harga' => 50000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 20,
            'terjual' => 0,
            'berat' => 100,
            'gambar' => '',
            'kategori_id' => 1,
            'toko_id' => 1,
            'halaman' => 412,
            'publisher' => 'KORANBOGOR.com'
        ],[
            'nama' => 'jika kita tidak pernah jatuh cinta',
            'harga' => 35000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 20,
            'terjual' => 0,
            'berat' => 100,
            'gambar' => '',
            'kategori_id' => 1,
            'toko_id' => 1,
            'halaman' => 232,
            'publisher' => 'GagasMedia',
        ],[
            'nama' => 'Selena Nebula',
            'harga' => 65000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 20,
            'terjual' => 0,
            'berat' => 100,
            'gambar' => '',
            'kategori_id' => 1,
            'toko_id' => 1,
            'halaman' => 365,
            'publisher' => 'Gramedia', 
        ],[
            'nama' => 'senja & pagi',
            'harga' => 40000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 20,
            'terjual' => 0,
            'berat' => 100,
            'gambar' => '',
            'kategori_id' => 1,
            'toko_id' => 1,
            'halaman' => 200,
            'publisher' => 'Loveable x Bhumi Anoma',
        ],[
            'nama' => 'rusak saja buku ini',
            'harga' => 30000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 20,
            'terjual' => 0,
            'berat' => 100,
            'gambar' => '',
            'kategori_id' => 1,
            'toko_id' => 1,
            'halaman' => 180,
            'publisher' => 'Anak Hebat Indonesia',
        ],[
            'nama' => 'wanita berakhir surga',
            'harga' => 55000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 20,
            'terjual' => 0,
            'berat' => 100,
            'gambar' => '',
            'kategori_id' => 1,
            'toko_id' => 1,
            'halaman' => 180,
            'publisher' => 'ALFATIH PRESS',
        ],[
            'nama' => 'kisah tanah jawa',
            'harga' => 250000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 20,
            'terjual' => 0,
            'berat' => 100,
            'gambar' => '',
            'kategori_id' => 1,
            'toko_id' => 1,
            'halaman' => 142,
            'publisher' => 'lainnya',
        ],[
            'nama' => 'my lecture my husband',
            'harga' => 22000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 20,
            'terjual' => 0,
            'berat' => 100,
            'gambar' => '',
            'kategori_id' => 1,
            'toko_id' => 1,
            'halaman' => 266,
            'publisher' => 'Buku Kita',
        ],[
            'nama' => 'mencintaimu dalam doa',
            'harga' => 60000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 20,
            'terjual' => 0,
            'berat' => 100,
            'gambar' => '',
            'kategori_id' => 1,
            'toko_id' => 1,
            'halaman' => 215,
            'publisher' => 'Grass Media',
        ],[
            'nama' => 'galaksi',
            'harga' => 30000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 20,
            'terjual' => 0,
            'berat' => 100,
            'gambar' => '',
            'kategori_id' => 1,
            'toko_id' => 1,
            'halaman' => 492,
            'publisher' => 'Coconuts Books',
        ],[
            'nama' => 'garis waktu',
            'harga' => 30000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 20,
            'terjual' => 0,
            'berat' => 100,
            'gambar' => '',
            'kategori_id' => 1,
            'toko_id' => 1,
            'halaman' => 212,
            'publihser' => 'Media Kita',
        ],[
            'nama' => 'secrets',
            'harga' => 30000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 20,
            'terjual' => 0,
            'berat' => 100,
            'gambar' => '',
            'kategori_id' => 1,
            'toko_id' => 1,
            'halaman' => 334,
            'publisher' => 'Kubus Media',
        ],[
            'nama' => 'teluk alaska',
            'harga' => 25000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 20,
            'terjual' => 0,
            'berat' => 100,
            'gambar' => '',
            'kategori_id' => 1,
            'toko_id' => 1,
            'halaman' => 408,
            'publisher' => 'Coconuts Books',
        ],[
            'nama' => 'kamu terlalu banyak bercanda',
            'harga' => 33000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 20,
            'terjual' => 0,
            'berat' => 100,
            'gambar' => '',
            'kategori_id' => 1,
            'toko_id' => 1,
            'halaman' => 194,
            'publisher' => 'Kebahagiaan Itu Sederhana',
        ],[
            'nama' => 'inquieto',
            'harga' => 30000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 20,
            'terjual' => 0,
            'berat' => 100,
            'gambar' => '',
            'kategori_id' => 1,
            'toko_id' => 1,
            'halaman' => 646,
            'publisher' => 'Kubus Media',
        ],[
            'nama' => 'janur ireng',
            'harga' => 32000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 20,
            'terjual' => 0,
            'berat' => 100,
            'gambar' => '',
            'kategori_id' => 1,
            'toko_id' => 1,
            'halaman' => 340,
            'publisher' => 'Bukune',
        ],[
            'nama' => 'next',
            'harga' => 30000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 20,
            'terjual' => 0,
            'berat' => 100,
            'gambar' => '',
            'kategori_id' => 1,
            'toko_id' => 1,
            'halaman' => 220,
            'publisher' => 'Loveable',
        ],[
            'nama' => 'Reon Komik #35',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 250,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'Reon Komik #20',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 250,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'Reon Komik #09',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 250,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'Reon Komik #27',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 250,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'Reon Komik #11',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 250,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'Reon Komik #22',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 250,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'Reon Komik #33',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 250,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'Reon Komik #08',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 250,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'SHIVERS 05',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 250,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'Reon Komik #14',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 250,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'Reon Komik #05',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 250,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'Reon Komik #23',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 250,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'Reon Komik #31',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 250,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'Reon Komik Vol 13',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 250,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'Reon Komik #07',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 250,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'Reon Komik #25',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 250,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'Reon Komik #38',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 250,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'Big Slacker Baby',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 280,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'SHIVERS 03',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 280,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'SHIVERS 04',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 280,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'SHIVERS 02',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 280,
            'publisher' => 'Remaja',
        ],[
            'nama' => 'Guardian Devil',
            'harga' => 10000, 
            'Deskripsi' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio unde earum ducimus atque quam incidunt, autem doloribus dolor distinctio neque in eos tenetur sapiente, libero, non laudantium placeat et similique?',
            'stok' => 30,
            'terjual' => 0,
            'berat' => 150,
            'gambar' => '',
            'kategori_id' => 4,
            'toko_id' => 1,
            'halaman' => 250,
            'publisher' => 'Remaja',
        ]]);
    }
}
